### PR TITLE
settings folder as per updated atom api

### LINKED ISSUE #5: Package.loadSettings is deprecated.
Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:552:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:168:43)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:161:12)
```

### PR DESCRIPTION
**Pull request by larsenwork**
Closes #5, #6, #7, #8, #9, #10, #11, #12, #13

### CODE REVIEW

**Comment by larsenwork** [comment]
ping @P233

**Comment by thibmaek** [comment]
+1 please merge

**Comment by larsenwork** [comment]
@thibmaek one of us might fork and add this to atom if @P233 has abandoned ship?

**Comment by thibmaek** [comment]
@larsenwork yeah but then we'd have to change the name of the package right? Current users wouldnt get the update?

**Comment by larsenwork** [comment]
@thibmaek jep, not ideal...let's wait and hopefully @P233 resurfaces

**Comment by thibmaek** [comment]
@larsenwork Now that I think of it I kinda rely heavily on this package. Seems like author is not showing up anytime soon, I'll fork, update the API and publish to apm later today.

**Comment by thibmaek** [comment]
Found the time sooner than I thought 😅
- https://atom.io/packages/Sass-Syntax-Highlight
- `apm install sass-syntax-highlight`

**Comment by larsenwork** [comment]
@thibmaek later today as in now:

screen shot 2015-06-13 at 12 07 30

**Comment by larsenwork** [comment]
brilliant

**Pull request closed without merging**
